name: parseValidationTests

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Validate Json Files in parse Directory
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8.12"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install --upgrade pip &&
          pip install -r requirements_test.txt
      - name: Run pyTest to Validate JSON Files
        run: pytest tests/test_validate_json.py
